# Generated by Django 4.2.8 on 2024-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-written_in'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='projects_em_name_e3f37b_idx'),
        ),
    ]
